### ISSUE TITLE
suggest adding "zenty"

### ISSUE THREAD

**Issue by robertspark** [joco-nz/lcnc-bullseye-installer#2]
Just done a debian bullseye 11.2 iso install, and then run the script {still running}.

I noticed that zenty was required and is not preinstalled with bullseye so suggest maybe adding it somewhere near the start of the script so that it could be used later.

Nice work on the scripts, thanks,

**Comment by joco-nz** [comment]
The recommendation is to use a "non free" iso version so as to remove issues with network drivers. 
I recommend and use:  https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/11.2.0-live+nonfree/amd64/iso-hybrid/debian-live-11.2.0-amd64-xfce+nonfree.iso

Zenity is on this image.

**Comment by robertspark** [comment]
I am using the nonfree iso, but this one and select xfce, and it does not include zenity 

https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/11.2.0+nonfree/amd64/iso-cd/firmware-11.2.0-amd64-netinst.iso

I will try your image as I cannot get probe basic to run now as something is broken or missing in qtpyvcp

**Comment by joco-nz** [comment]
There is an issue with dependency missmatch in a python package being used. The pypy recipes are not correctly managing this.  Probably because the breaking change is new.  We are looking to see if we can fix it through our python setup script.

The dependency issue is:
markupsafe has removed something that jinja2 tries to import. jinja2 is used in the yaml parsing code.

**Comment by joco-nz** [comment]
This issue seems to have been resolved now as I have been doing clean install tests today with no issues.
